name: Bot Hosting

on:
  push:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - name: Run client.js
          run: node client.js
